version: '3.1'

services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/


volumes:
  database-data: 
    # named volumes can be managed easier using docker-compose
    # this volume needs to be set first, in order for the container 
    # be able to use it.
